config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  resources :users
  resources :sessions
  namespace :admin do
    resources :books
  end
  resources :books
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!
  attr_accessor :password, :password_confirmation

  validates_presence_of :email, message: "邮箱不能为空"
  validates :email, uniqueness: true
  validates_presence_of :password, message: "密码不能为空",
    if: :need_validate_password
  validates_presence_of :password_confirmation, message: "密码确认不能为空",
    if: :need_validate_password
  validates_confirmation_of :password, message: "密码不一致",
    if: :need_validate_password
  validates_length_of :password, message: "密码最短6位",
    minimum: 6,
    if: :need_validate_password

  private

  def need_validate_password
    self.new_record? ||
      (!self.password.nil? or !self.password_confirmation.nil?)
  end
end

app/controllers/admin/books_controller.rb
class Admin::BooksController < ApplicationController
  def index
    @books = Book.all
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)

    if @book.save
      redirect_to book_path(@book)
    else
      render "new"
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])

    if @book.update(book_params)
      redirect_to admin_books_path
    else
      render "new"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy

    redirect_to admin_books_path
  end

  private

  def book_params
    params.require(:book).permit!#(:title, :text, :book_stock)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :auth_user, except: [:destroy]

  def new
  end

  def create
    #login是sorcery的登录方法
    if user = login(params[:email], params[:password])
      flash[:notice] = '登陆成功'
      redirect_to root_path
    else
      flash[:notice] = "邮箱或者密码错误"
      redirect_to new_session_path
    end
  end

  def destroy
    #logout是sorcery的退出方法
    logout
    flash[:notice] = "退出登陆"
    redirect_to root_path
  end

  private

  def auth_user
    #logged_in?是sorcery的判断登录方法
    if logged_in?
      redirect_to root_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  #用户注册
  def create
    @user = User.new(params.require(:user)
      .permit(:email, :password, :password_confirmation))

    if @user.save
      flash[:notice] = '注册成功，请登录'
      redirect_to new_session_path
    else
      render action: :new
    end
  end

  #用户密码修改
  def change_password
    if current_user.valid_password?(params[:old_password])
      current_user.password_confirmation = params[:password_confirmation]

      if current_user.change_password!(params[:password])
        render json: {status: 'ok', msg: '密码修改成功'}
      else
        render json: {status: 'error', msg: current_user.errors.messages.values.flatten}
      end
    else
      render json: {status: 'error', msg: '旧密码不正确'}
    end
  end

  #用户发送忘记密码邮件,这里需要对邮件进行配置
  def send_forget_password_email
    @user = User.find_by(email: params[:email])
    if @user
      @user.deliver_reset_password_instructions!
      render json: {status: 'ok', msg: "重置密码的链接已发送到上面的邮箱"}
    else
      render json: {status: 'error', msg: '指定邮箱不存在'}
    end
  end

  #密码重置
  def reset_password
    @user = User.load_from_reset_password_token(params[:token])
    if @user
      @user.password_confirmation = params[:password_confirmation]
      if @user.change_password!(params[:password])
        render json: {status: 'ok', msg: '密码修改成功'}
      else
        render json: {status: 'error', msg: @user.errors.messages.values.flatten}
      end
    else
      render json: {status: 'error', msg: 'token不正确或者已过期'}
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/books/edit.html.erb
<h1>图书编辑</h1>
<%= form_for [:admin, @book] do |f| %>
  <p>
    <%= f.label "书名" %>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label "简介" %>
    <%= f.text_area :text %>
  </p>

  <p>
    <%= f.label "库存" %>
    <%= f.number_field :book_stock %>
  </p>

  <p>
    <%= f.submit "提交" %>
  </p>
<% end %>

app/views/admin/books/index.html.erb
<p>
  <%= link_to "新书上架", new_admin_book_path %>
</p>

<table class="table table-bordered table-hover">
  <tr class="text-info">
    <th>书名</th>
    <th>简介</th>
    <th>库存</th>
    <th>操作</th>
  </tr>
  <% @books.each do |book| %>
    <tr>
      <td><%= book.title %></td>
      <td><%= book.text %></td>
      <td><%= book.book_stock %></td>
      <td>
        <%= link_to "显示", book_path(book) %> <span style="margin-left: 5px">|</span>
        <%= link_to "编辑", edit_admin_book_path(book) %> <span style="margin-left: 5px">|</span>
        <%= link_to "删除", admin_book_path(book),
            method: :delete, data: { confirm: "确定删除本书？"} %>
    </tr>
  <% end %>
</table>

app/views/admin/books/new.html.erb
<h1>新书上线</h1>
<%= form_for [:admin, @book] do |f| %>
  <p>
    <%= f.label "书名" %>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label "简介" %>
    <%= f.text_area :text %>
  </p>

  <p>
    <%= f.label "库存" %>
    <%= f.number_field :book_stock %>
  </p>

  <p>
    <%= f.submit "提交" %>
  </p>
<% end %>

app/views/books/show.html.erb
<h1>图书展示</h1>
<p>
  <strong>书名:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>简介:</strong>
  <%= @book.text %>
</p>

<p>
  <strong>库存:</strong>
  <%= @book.book_stock %>
</p>

app/views/common/_footer.html.erb
<footer class="container-fluid navbar-fixed-bottom" style="margin-top: 100px;">
  <p class="text-center">
    图书管理系统
    <br>Placnk1043
  </p>
</footer>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
        <a class="navbar-brand" href="/">图书管理系统</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <li>
          </li>
          <% if current_user.nil? %>
            <li><%= link_to("注册", new_user_path) %> </li>
            <!-- 在 rails 中 "link_to" 是 "<a>" 的封装 -->
            <li><%= link_to("登入", new_session_path) %></li>
          <% else %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Hi!, <%= current_user.email %>
                  <b class="caret"></b>
              </a>
              <ul>
                <li><%= link_to "后台", admin_books_path %></li>
                <li> <%= link_to("登出", session_path(session),
                        method: :delete, data: { confirm: '确认退出吗?' } ) %> </li>
              </ul>
            </li>
          <% end %>
        </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails05</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
      <%= render "common/navbar" %>
      <%= yield %>
    </div>
    <%= render "common/footer" %>
  </body>
</html>

app/views/users/new.html.erb
<h1>用户注册</h1>
<div>
  <% unless @user.errors.empty? %>
    <ul>
      <% @user.errors.messages.values.flatten.each do |error| %>
        <li><%= error %></li>
      <% end -%>
    </ul>
  <% end -%>
</div>
<%= form_for :user, url: users_path, method: :post, html: { class: 'form-horizontal', id: "user_form"} do |f| %>
  <div class="form-group">
    <div class="col-lg-12">邮箱 *</div>
    <div class="col-lg-12">
      <%= f.text_field :email, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-lg-12">密码 *</div>
    <div class="col-lg-12">
      <%= f.password_field :password, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-lg-12">密码确认 *</div>
    <div class="col-lg-12">
      <%= f.password_field :password_confirmation, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-lg-12">
      <div class="text-center">
        <a href="<%= new_session_path %>">登录</a>
      </div>
    </div>
  </div>
  <div class="form-group">
    <div class="col-lg-12">
      <input type="submit" name="create_user_submit" value="创建账户" class="col-xs-12 btn btn-primary">
    </div>
  </div>
<% end %>

app/views/welcome/index.html.erb
<h1>Hello World</h1>